# --------------------------
# Docker Compose Override for Local Development
# --------------------------

services:
  # --------------------------
  # App container overrides
  # --------------------------
  app:
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    volumes:
      - ./src:/var/www/html
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        INSTALL_XDEBUG: true

  # --------------------------
  # Queue worker for Laravel jobs
  # --------------------------
  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${PROJECT_NAME}-queue
    command: php artisan queue:work
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - adminoxlaravel_network

  # --------------------------
  # Scheduler for Laravel cron jobs
  # --------------------------
  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${PROJECT_NAME}-scheduler
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - adminoxlaravel_network

# Define networks in override as well
networks:
  adminoxlaravel_network:
    name: ${PROJECT_NAME}_network
    driver: bridge